In [1]:
import numpy as np

## Create 2 dim arrays

In [2]:
first = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
first

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
first.shape

(2, 3)

In [4]:
first.ndim

2

In [5]:
second = np.array(
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
)
second

array([[ 7,  8,  9],
       [10, 11, 12]])

## Math opetarions

In [6]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [7]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [8]:
first / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

## Axes in arrays

### 1 Dimension

In [9]:
one_dim = np.array([1, 2, 3, 4])

In [10]:
one_dim.shape

(4,)

![1 dimension axes](./images/1dim_axes.jpg)

### 2 Dimensions

In [11]:
two_dim = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [12]:
two_dim.shape  # 2 in axis 0 and 3 in axis 1

(2, 3)

![2 dimension axes](./images/2dim_axes.jpg)

### 3 Dimensions

In [13]:
three_dim = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)

In [14]:
three_dim.shape

(2, 2, 3)

In [15]:
three_dim[1][0][2]

9

In [16]:
three_dim[1, 0, 2]

9

![3 dimension axes](./images/3dim_axes.jpg)

## Concat arrays by axis

### Concar 2 dim arrays

In [19]:
concatenated_arr = np.concatenate((first, second))
concatenated_arr  # as default concat by axes 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
concatenated_arr.shape

(4, 3)

In [21]:
concatenated_arr = np.concatenate((first, second), axis=1)
concatenated_arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [22]:
concatenated_arr.shape

(2, 6)

### Concat 1 dim arrays

In [24]:
np.concatenate((np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8])))

array([1, 2, 3, 4, 5, 6, 7, 8])