In [1]:
import numpy as np

### `np.zeros(tuple_shape, [dtype=arr_type])`

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.zeros((3, 4), dtype=bool)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

### `np.ones(tuple_shape, [dtype=arr_type])`

In [11]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.ones((3, 4), dtype=str)

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [24]:
np.ones((3, 4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

### `np.random`

#### np.random.random

In [43]:
np.random.seed(10)  # start for algo (you will have same nums)
np.random.random((2, 4))

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071]])

#### np.random.randint

In [63]:
np.random.seed(15)
np.random.randint(10, 20, size=(2, 4))  # randint(from, to, size=shape)

array([[18, 15, 15, 17],
       [10, 17, 15, 16]])

#### np.random.uniform

In [64]:
np.random.uniform(size=(3, 5))

array([[0.30591892, 0.30447436, 0.11174128, 0.24989901, 0.9176299 ],
       [0.26414685, 0.71777369, 0.86571503, 0.80707948, 0.21055058],
       [0.16724303, 0.04670639, 0.03942231, 0.20023081, 0.9985434 ]])

In [67]:
np.random.seed(10)
np.random.uniform(10.0, 50.0, size=(3, 5))

array([[40.85282573, 10.83007797, 35.3459294 , 39.9521553 , 29.94028049],
       [18.99186582, 17.92251459, 40.42122849, 16.76443346, 13.53359257],
       [37.41439273, 48.13573385, 10.15793065, 30.48769054, 42.50483847]])

#### np.random.choice

In [70]:
np.random.seed(10)
np.random.choice(np.array([1, 2, 3]), size=20)

array([2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 2, 3, 1, 2, 1, 3, 1, 3, 1, 1])