# Arrange, Reshape and Flatten

---
### Arrange
`np.arrange(start=from, [stop=to, step=step])`

In [2]:
import numpy as np

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(10, 15)

array([10, 11, 12, 13, 14])

In [5]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [ ]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [7]:
np.arange(start=-70, stop=25, step=10)

array([-70, -60, -50, -40, -30, -20, -10,   0,  10,  20])

---
### Reshape

`np.reshape(new array shape)`

You can't reshape array if it contains less or more elements then you declare in the shape

In [16]:
numpy_ndarray = np.arange(16)
numpy_ndarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
numpy_ndarray.reshape((2, 8))  # 2 * 8 = 16

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
numpy_ndarray.reshape((4, 4))  # 4 * 4 = 16

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
numpy_ndarray.reshape((2, 2, 4))   # 2 * 2 * 4 = 16

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [24]:
np.random.seed(10)  # not necessarily
np.random.random((10,)).reshape((2, 5))   # 2 * 5 = 10

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701],
       [0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981]])

In [30]:
np.random.random((11,)).reshape((2, 5))   # Error 2 * 5 = 10 != 11

ValueError: cannot reshape array of size 11 into shape (2,5)

---
### Flatten
`.flatten()` - any array to 1 dim array

In [31]:
np.random.randint(10, 18, (4, 3, 3)).flatten()

array([15, 11, 17, 13, 10, 10, 15, 11, 10, 15, 13, 13, 12, 17, 10, 15, 10,
       14, 17, 15, 16, 13, 11, 11, 16, 11, 15, 16, 15, 11, 11, 14, 17, 16,
       14, 17])