In [2]:
import numpy as np

### 001. Calculate total

In [3]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [4]:
quantites = np.array([10, 5, 8, 12, 3])
quantites

array([10,  5,  8, 12,  3])

In [6]:
total_per_product = prices * quantites
total_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [9]:
# total_per_product.sum()
# or
total = np.sum(total_per_product)
total

664.62

### 002. Analysing blog post stats

In [10]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [11]:
max_views = np.max(views)
max_views

1200

In [12]:
min_views = np.min(views)
min_views

300

In [14]:
average_views = np.round(np.mean(views), 2)
average_views

733.33

In [15]:
total_views = np.sum(views)
total_views

4400