In [2]:
import numpy as np

### 001. Splitting Order into Batches

In [4]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009])

In [8]:
batches = np.split(order_ids, 3)
batches

[array([1001, 1002, 1003]),
 array([1004, 1005, 1006]),
 array([1007, 1008, 1009])]

In [9]:
for batch in batches:
    print(batch)

[1001 1002 1003]
[1004 1005 1006]
[1007 1008 1009]


In [11]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}")
    print(f"First element {batch[0]}")
    print(f"Second number {batch[1]}")
    print(f"Third number {batch[2]}")

Batch number 0
First element 1001
Second number 1002
Third number 1003
Batch number 1
First element 1004
Second number 1005
Third number 1006
Batch number 2
First element 1007
Second number 1008
Third number 1009


### 002. Categorizing Product Ratings

In [12]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [16]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [17]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])