In [223]:
import numpy as np

### 001. Calculate Total and Average quantities sold

In [224]:
# Each column is specific product
# Each row is specific order
order_quantities = np.array(
    [
        [5, 3, 2, 7], # Order 001
        [10, 6, 3, 9] # Order 002
    ]
)
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

![example](./images/007_01_examples.jpg)

In [225]:
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [226]:
total_quantities_sold = np.sum(order_quantities, axis=1)
total_quantities_sold

array([17, 28])

In [227]:
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

### 002. Calc average product ratings and maximum rating per category

In [261]:
# Each row is one product
# Each product is rated in 4 categories
np.random.seed(4)
# genarated_product_raitings = np.random.randint(0, 50, size=(3, 4)) / 10
genarated_product_raitings = np.round(np.random.uniform(0.0, 5., size=(3, 4)), 2)
genarated_product_raitings

array([[4.84, 2.74, 4.86, 3.57],
       [3.49, 1.08, 4.88, 0.03],
       [1.26, 2.17, 3.9 , 0.99]])

In [265]:
average_raiting_per_category = np.round(np.mean(genarated_product_raitings, axis=0), 2)
average_raiting_per_category

array([3.2 , 2.  , 4.55, 1.53])

In [266]:
average_raiting_per_product = np.round(np.mean(genarated_product_raitings, axis=1), 2)
average_raiting_per_product

array([4.  , 2.37, 2.08])

In [264]:
max_raiting_per_category = np.max(genarated_product_raitings, axis=0)
max_raiting_per_category

array([4.84, 2.74, 4.88, 3.57])