In [1]:
import numpy as np

### 001. Generation of the sample stock data

In [9]:
companies = ['Google', 'Microsoft', 'Apple']
days = ["Mon 1 April", "Tue 2 April"]
prices = ['Open', 'Close', 'High', 'Low']

In [10]:
np.random.seed(1)
stock_prices = np.round(
    np.random.random(
        (len(companies), len(days), len(prices))
    ), 3
)
stock_prices

array([[[0.417, 0.72 , 0.   , 0.302],
        [0.147, 0.092, 0.186, 0.346]],

       [[0.397, 0.539, 0.419, 0.685],
        [0.204, 0.878, 0.027, 0.67 ]],

       [[0.417, 0.559, 0.14 , 0.198],
        [0.801, 0.968, 0.313, 0.692]]])

In [11]:
stock_prices.shape

(3, 2, 4)

In [25]:
sort_prices = np.zeros(stock_prices.shape)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [47]:
sort_prices = stock_prices.copy()
for i, company in enumerate(companies):
    for j, day in enumerate(days):
        stock_prices[i, j].sort()

        # Switch lowest and open price
        it_will_be_open_price = stock_prices[i, j, 2]
        stock_prices[i][j][2] = stock_prices[i][j][0]
        stock_prices[i][j][0] = it_will_be_open_price

        # Switch lowest and highest
        it_will_be_highest_price = stock_prices[i][j][3]
        stock_prices[i][j][3] = stock_prices[i][j][2]
        stock_prices[i][j][2] = it_will_be_highest_price

stock_prices = sort_prices.copy()
stock_prices

array([[[0.417, 0.302, 0.72 , 0.   ],
        [0.186, 0.147, 0.346, 0.092]],

       [[0.539, 0.419, 0.685, 0.397],
        [0.67 , 0.204, 0.878, 0.027]],

       [[0.417, 0.198, 0.559, 0.14 ],
        [0.801, 0.692, 0.968, 0.313]]])

In [45]:
for i, company in enumerate(companies):
    print(f"Stock prices for the {company}:")
    for j, day in enumerate(days):
        print(f"  Stock on {day}")
        for k, price in enumerate(prices):
            print(f"    {price}: {stock_prices[i, j, k]}")
    print('')

Stock prices for the Google:
  Stock on Mon 1 April
    Open: 0.417
    Close: 0.302
    High: 0.72
    Low: 0.0
  Stock on Tue 2 April
    Open: 0.186
    Close: 0.147
    High: 0.346
    Low: 0.092

Stock prices for the Microsoft:
  Stock on Mon 1 April
    Open: 0.539
    Close: 0.419
    High: 0.685
    Low: 0.397
  Stock on Tue 2 April
    Open: 0.67
    Close: 0.204
    High: 0.878
    Low: 0.027

Stock prices for the Apple:
  Stock on Mon 1 April
    Open: 0.417
    Close: 0.198
    High: 0.559
    Low: 0.14
  Stock on Tue 2 April
    Open: 0.801
    Close: 0.692
    High: 0.968
    Low: 0.313



In [43]:
stock_prices.ndim

3